### PR TITLE
fix analysisCRS to use network layer, fix OD matrix unique ID data types, and update language to match other QGIS functions

### PR DESCRIPTION
**Pull request by josephholler**
Updates language in graphic interface and some field names in response to issue #32 

Fixes issue #31  to allow for different data types in the OD Matrix unique ID's.

May fix issue #29 by always using the network layer's CRS for analysis.

Clarifies some of the ambiguity of units mentioned in issue #17 , but so far this pull request is focused on the input units for Iso-Areas. More work is needed to clarify output units of time and distance and input units for speed, especially if the CRS uses linear units other than meters.

### CODE REVIEW

**Comment by root676** [comment]
@josephholler thank you very much for the PR! I will review it in detail when I have more time (my calendar is really full right now). I'll keep you posted! :)

**Comment by root676** [comment]
@josephholler I just left some comments at the referenced issues - lets discuss the changes there before returning to an in-depth review of the PR.

**Comment by josephholler** [comment]
Just saw that Kufre pushed the changes for #34 here: db7f78a

**Comment by root676** [comment]
@josephholler I am a little confused. Did you move the changes of this PR also to PR #37 ? If all changes of this PR are present in #37 , could you please close this one.

**Comment by josephholler** [comment]
Yes, #37 is composed of a new set of commits on the same branch as this PR. I'll close this and leave #37 open.

**Pull request closed without merging**
